version: "3.6"
services:
  nest-tpl:
    build: .
    container_name: nest-tpl
    environment:
      NODE_ENV: "development"
    deploy:
      resources:
        limits:
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    #networks:
    #  - code-push-net
    network_mode: host
    #volumes:
    #  - data-nest:/app

#networks:
#volumes:
#  data-nest:
