version: "3.6"
services:
  nest-tpl:
    build: .
    container_name: nest-tpl
    environment:
      NODE_ENV: "development"
    deploy:
      resources:
       limits:
         memory: 1000M
      restart_policy:
       condition: on-failure
    ports:
      - "3002:3002"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  # db:
  #   container_name: postgres
  #   image: postgres:12-alpine
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_DB: "nesttpl"
  #     POSTGRES_PASSWORD: "7895432dB" #密码
  #     PGDATA: "/var/lib/postgresql/data/pgdata" #数据存储文件夹
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data/pgdata
  #     #- ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  db:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234abcg"
      MYSQL_DATABASE: "nesttpl"
      TZ: Asia/Shanghai
    deploy:
      restart_policy:
        condition: on-failure
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      #- ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:80

  redis:
    container_name: redis
    image: redis:5-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - "6388:6379"

  # hasura:
  #   container_name: hasura
  #   image: hasura/graphql-engine:latest
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   restart: always
  #   environment:
  #     HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:7895432dB@db:5432/nesttpl
  #     HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  #     HASURA_GRAPHQL_ADMIN_SECRET: "himyhasura"

